import psycopg2
conn = psycopg2.connect('host=postgres dbname=dify user=wibsite password=wibsite_pass')
cur = conn.cursor()
cur.execute('SELECT id, name, email, status FROM accounts ORDER BY created_at')
rows = cur.fetchall()
print('Accounts:', rows)
cur.execute("SELECT id, name FROM tenants ORDER BY created_at")
tenants = cur.fetchall()
print('Tenants:', tenants)
cur.execute('SELECT id, tenant_id, account_id, role FROM tenant_account_joins')
joins = cur.fetchall()
print('TenantJoins:', joins)
cur.close()
conn.close()
