const bcrypt = require('/usr/local/lib/node_modules/n8n/node_modules/.pnpm/bcryptjs@2.4.3/node_modules/bcryptjs');
const storedHash = '$2a$10$Eu4MBug4KLsBMl0hNsnZ3uFo6pNfOSDqNup3DeRyQMeYHb0mOUniS';
console.log('Testing stored hash:');
console.log('  Admin@123:', bcrypt.compareSync('Admin@123', storedHash));
console.log('  password:', bcrypt.compareSync('password', storedHash));
console.log('  admin:', bcrypt.compareSync('admin', storedHash));
console.log('  n8n:', bcrypt.compareSync('n8n', storedHash));
console.log('  test:', bcrypt.compareSync('test', storedHash));
console.log('  Wibsite2024:', bcrypt.compareSync('Wibsite2024', storedHash));
console.log('  Wibsite1:', bcrypt.compareSync('Wibsite1', storedHash));
