# ═══════════════════════════════════════════════════════════════
# gitlab-upsert-issues.ps1 — Herramienta de carga/actualización de issues en GitLab
#
# Carga los roadmaps MD (funcionalidades F1-F5 + mejoras C/K/L/R/A/D)
# como issues estandarizados en el proyecto sales-ai-platform/wibsite.
#
# USO:
#   1. Editar los bloques Add-Issue de este script (agregar/modificar issues)
#   2. Ejecutar desde la raíz del repo wibsite:
#        powershell -NoProfile -ExecutionPolicy Bypass -File .\scripts\gitlab\gitlab-upsert-issues.ps1
#      O bien (para preservar UTF-8 del script sin BOM):
#        $c = [IO.File]::ReadAllText('.\scripts\gitlab\gitlab-upsert-issues.ps1', [Text.Encoding]::UTF8); Invoke-Expression $c
#   3. Verificar salida: todas las líneas "OK #iid" (HTTP 2xx).
#
# REGLAS:
#   - NO usar Invoke-RestMethod para enviar texto con acentos: PS 5.1 corrompe
#     el body UTF-8 (mojibake). Este script usa curl.exe + JSON escapado \uXXXX.
#   - El token se toma del remote gitlab (git config remote.gitlab.url).
#   - El mapeo issue->iid es POR ORDEN de llamadas Add-Issue: mantener el orden
#     de las llamadas si se re-ejecuta para actualizar (PUT) en vez de duplicar.
#   - Detalle completo del flujo: docs/GITLAB-ISSUE-WORKFLOW.md
#
# Generado: 27/08/2026 · última ejecución exitosa: carga de 77 issues (#17-#93)
# ═══════════════════════════════════════════════════════════════
$ErrorActionPreference = 'Continue'
$base = 'http://127.0.0.1:9080/api/v4'
$projectId = 1
$remote = git config --get remote.gitlab.url
$token = ($remote -replace '.*oauth2:(.*)@.*', '$1')
$headers = @{ 'PRIVATE-TOKEN' = $token }
$TMPDIR = $env:TEMP

function ConvertTo-AsciiJson {
  param($Obj)
  $json = $Obj | ConvertTo-Json -Compress -Depth 8
  $sb = New-Object System.Text.StringBuilder
  foreach ($ch in $json.ToCharArray()) {
    $code = [int]$ch
    if ($code -gt 0x7E) {
      [void]$sb.Append('\u')
      [void]$sb.Append($code.ToString('X4'))
    } else {
      [void]$sb.Append($ch)
    }
  }
  return $sb.ToString()
}

function Invoke-GitLab {
  param([string]$Method, [string]$Path, [hashtable]$Body = $null)
  if ($Body) {
    $json = ConvertTo-AsciiJson $Body
    $tmp = Join-Path $TMPDIR ("gl-" + [guid]::NewGuid().ToString('N') + '.json')
    [System.IO.File]::WriteAllText($tmp, $json, (New-Object System.Text.UTF8Encoding($false)))
    $out = & curl.exe -s -w "`nHTTPCODE:%{http_code}" -X $Method "$base$Path" -H "PRIVATE-TOKEN: $token" -H "Content-Type: application/json" --data-binary "@$tmp"
    Remove-Item $tmp -Force -ErrorAction SilentlyContinue
    $statusLine = ($out | Select-Object -Last 1)
    if ($statusLine -match 'HTTPCODE:(\d+)') { return $Matches[1] }
    return '0'
  } else {
    $out = & curl.exe -s -w "`nHTTPCODE:%{http_code}" -X $Method "$base$Path" -H "PRIVATE-TOKEN: $token"
    $statusLine = ($out | Select-Object -Last 1)
    if ($statusLine -match 'HTTPCODE:(\d+)') { return $Matches[1] }
    return '0'
  }
}

# ── 1. Mapear milestones existentes (ids 2-11 por orden de creación) ──
$allMs = Invoke-RestMethod -Uri "$base/projects/$projectId/milestones?per_page=100" -Headers $headers
$myMs = @($allMs | Where-Object { $_.id -ge 2 -and $_.id -le 11 } | Sort-Object id)
Write-Output "Milestones a reparar: $($myMs.Count)"

$milestones = @(
  @{ title = 'Oleada 0 - Cimientos de datos';              start = '2026-08-27'; due = '2026-09-04'; desc = 'PG primario, índices, normalización y archivado de conversaciones. Prerequisito de todo el roadmap.' },
  @{ title = 'Oleada 1 - Ciclo de vida del lead (F1)';     start = '2026-09-07'; due = '2026-09-18'; desc = 'Etapas claras (primer contacto -> comprador), transiciones validadas, perfil 360 y dedup.' },
  @{ title = 'Oleada 2 - Grupos y segmentos (F2/F3)';      start = '2026-09-21'; due = '2026-10-02'; desc = 'Grupos manuales con agrupador IA + segmentos dinámicos con job continuo.' },
  @{ title = 'Oleada 3 - Campañas inteligentes';           start = '2026-10-05'; due = '2026-10-16'; desc = 'Audiencia por segmento, bloqueo opt-out, A/B, eventos, dry-run, rate-limit.' },
  @{ title = 'Oleada 4 - Respuestas automáticas';          start = '2026-10-19'; due = '2026-10-30'; desc = 'Bienvenida/fuera de horario, snippets, comandos, handoff inmediato, validación del grafo.' },
  @{ title = 'Oleada 5 - Copiloto y asignación';           start = '2026-11-02'; due = '2026-11-13'; desc = 'Copiloto IA en chat, handoff con contexto, asignación automática, resúmenes.' },
  @{ title = 'Oleada 6 - Calendario y seguimiento (F4)';   start = '2026-11-16'; due = '2026-11-27'; desc = 'Motor de cadencias ejecutable, eventos automáticos, vista por fecha con cards por grupo, SLAs.' },
  @{ title = 'Oleada 7 - Cierre: auditoría y UX';          start = '2026-11-30'; due = '2026-12-11'; desc = 'Atribución, feedback al score, predicción, webhooks, auditoría completa, GDPR.' },
  @{ title = 'Oleada 8 - Consolidación (F5)';              start = '2026-12-14'; due = '2026-12-23'; desc = 'Agente plantillero + suite e2e integral + actualización documental completa.' },
  @{ title = 'Pospuestos - Dependencias externas';         start = $null;        due = $null;        desc = 'Requerirá Twenty bidireccional, SaaS multi-tenant o APIs externas. Se reactivan cuando esas dependencias existan.' }
)
$global:msMap = @{}
for ($i = 0; $i -lt $milestones.Count; $i++) {
  $id = $myMs[$i].id
  $m = $milestones[$i]
  $body = @{ title = $m.title; description = $m.desc }
  if ($m.start) { $body.start_date = $m.start }
  if ($m.due) { $body.due_date = $m.due }
  $status = Invoke-GitLab 'PUT' "/projects/$projectId/milestones/$id" $body
  $global:msMap[$m.title] = $id
  if ($status -match '^2') { Write-Output "MS reparado: [$id] $($m.title)" } else { Write-Output "MS ERROR [$id] => HTTP $status" }
}

# ── 2. Borrar milestones de prueba (12, 13, 14) ──
foreach ($tid in @(12, 13, 14)) {
  $status = Invoke-GitLab 'DELETE' "/projects/$projectId/milestones/$tid"
  Write-Output "Milestone test $tid eliminado (HTTP $status)"
}

# ── 3. Reparar labels ──
$labels = @(
  @{ name = 'area::campaigns';     color = '#F39C12'; description = 'Campañas broadcast y segmentación de audiencia' },
  @{ name = 'area::contacts';      color = '#1ABC9C'; description = 'Gestión de contactos, perfiles, dedup, tags' },
  @{ name = 'area::leads';         color = '#9B59B6'; description = 'Ciclo de vida del lead, etapas, scoring' },
  @{ name = 'area::responses';     color = '#3498DB'; description = 'Respuestas automáticas, comandos, KB, multimedia' },
  @{ name = 'area::agents';        color = '#E67E22'; description = 'Copiloto, handoff, cadencias, asignación de operadores' },
  @{ name = 'area::calendar';      color = '#E91E63'; description = 'Calendario de seguimientos, eventos, SLAs' },
  @{ name = 'area::templates';     color = '#2ECC71'; description = 'Plantillas de mensaje y generación con IA' },
  @{ name = 'area::consolidation'; color = '#7B8A9E'; description = 'Cierres de oleada, e2e integral, documentación' },
  @{ name = 'type::validation';    color = '#16A085'; description = 'Funcionalidad ya implementada en código: validar y exponer' },
  @{ name = 'roadmap::f1';         color = '#C0392B'; description = 'Idea de usuario F1: etapas claras del ciclo de vida del lead' },
  @{ name = 'roadmap::f2';         color = '#D35400'; description = 'Idea de usuario F2: grupos manuales + agrupador IA' },
  @{ name = 'roadmap::f3';         color = '#8E44AD'; description = 'Idea de usuario F3: segmentación activa por agente' },
  @{ name = 'roadmap::f4';         color = '#2980B9'; description = 'Idea de usuario F4: calendario de seguimientos' },
  @{ name = 'roadmap::f5';         color = '#27AE60'; description = 'Idea de usuario F5: plantillas recomendadas por IA' }
)
foreach ($l in $labels) {
  $enc = [uri]::EscapeDataString($l.name)
  $body = @{ new_name = $l.name; color = $l.color; description = $l.description }
  $status = Invoke-GitLab 'PUT' "/projects/$projectId/labels/$enc" $body
  if ($status -match '^2') { Write-Output "LB reparada: $($l.name)" } else { Write-Output "LB ERROR: $($l.name) => HTTP $status" }
}

# ── 4. Mapear issues existentes (iid 17-93 en orden de creación) ──
$allIssues = Invoke-RestMethod -Uri "$base/projects/$projectId/issues?per_page=100&sort=asc" -Headers $headers
$myIssues = @($allIssues | Where-Object { $_.iid -ge 17 -and $_.iid -le 93 } | Sort-Object iid)
Write-Output "Issues a reparar: $($myIssues.Count)"
$global:issueCounter = 0

function Add-Issue {
  param([hashtable]$i)
  $idx = $global:issueCounter
  $global:issueCounter++
  if ($idx -ge $myIssues.Count) { Write-Output "SKIP (sin iid): $($i.id)"; return }
  $iid = $myIssues[$idx].iid
  $milestoneId = $global:msMap[$i.milestone]
  $labelList = @(
    "area::$($i.area)",
    "priority::$($i.priority)",
    "status::$($i.status)",
    "type::$($i.type)"
  )
  if ($i.roadmap) { $labelList += $i.roadmap | ForEach-Object { "roadmap::$($_)" } }
  $labelsStr = ($labelList -join ',')

  $alcanceTxt = ($i.alcance | ForEach-Object { "- $_" }) -join "`n"
  $depsTxt = if ($i.deps.Count -gt 0) { $i.deps -join ', ' } else { '—' }
  $desbloqueaTxt = if ($i.desbloquea.Count -gt 0) { $i.desbloquea -join ', ' } else { '—' }
  $archTxt = ($i.archivos | ForEach-Object { "- $_" }) -join "`n"
  $checksTxt = ($i.checks | ForEach-Object { "- [ ] $_" }) -join "`n"
  $refsTxt = ($i.refs | ForEach-Object { "- $_" }) -join "`n"

  $desc = @"
## Contexto
$($i.contexto)

## Alcance
$alcanceTxt

## Relaciones
- Depende de: $depsTxt
- Desbloquea: $desbloqueaTxt
- Origen: $($i.origen)
- Oleada: $($i.milestone)

## Implementación objetivo
$archTxt

## Verificación (DoD)
$checksTxt

## Referencias
$refsTxt

## KPI
$($i.kpi)

---
*Issue generado desde los roadmaps MD el 27/08/2026. Estandar: contexto + alcance + relaciones + DoD + referencias.*
"@

  $title = "[$($i.prefix)] $($i.id) - $($i.title)"
  $body = @{ title = $title; description = $desc; labels = $labelsStr }
  if ($milestoneId) { $body.milestone_id = $milestoneId }
  $status = Invoke-GitLab 'PUT' "/projects/$projectId/issues/$iid" $body
  if ($status -match '^2') { Write-Output "OK  #$iid $title" } else { Write-Output "FAIL #$iid $title => HTTP $status" }
}

Write-Output '═════════ REPARANDO ISSUES (curl) ═════════'

# ═══════════════════════ OLEADA 0 ═══════════════════════
Add-Issue @{ prefix='TASK'; id='D1'; title='Cutover PostgreSQL primario y retirada del JSON store'; priority='critical'; status='backlog'; type='task'; area='data'; milestone='Oleada 0 - Cimientos de datos'; contexto='Los datos viven en JSON store con dual-write a PG (deuda OT-02). PG debe ser la fuente primaria para que jobs, segmentos y auditoría sean confiables. Relacionado con issue existente #5.'; alcance=@('Activar lecturas desde PG (flag STORE_MODE=pg) manteniendo dual-write','Migración completa de leads/campaigns/scores/opt-outs con conteos pre/post','Retirar fallback JSON solo tras verificación en runtime'); deps=@(); desbloquea=@('Oleadas 1-8 completas'); archivos=@('helper-node/services/store.js','helper-node/services/pgStore.js','scripts/campaigns-schema.sql','.env (STORE_MODE)'); checks=@('Smoke /api/internal/run-smoke verde','Conteos pre/post sin pérdidas','Suite Jest 176/22 en verde'); refs=@('ROADMAP-IMPLEMENTACION §2.6 D1, §4 Oleada 0','DATA-MASTER §10 (OT-02)','Issue GitLab #5'); kpi='0 pérdidas en migración'; origen='Investigación D1 (P0) + Fase A del roadmap' }

Add-Issue @{ prefix='TASK'; id='D2'; title='PK/FK reales e índices en tablas de campañas y leads'; priority='critical'; status='backlog'; type='task'; area='data'; milestone='Oleada 0 - Cimientos de datos'; contexto='El schema actual tiene gaps de PK/FK documentados en DATABASE-VALIDATION; sin ellos, dedup, grupos y eventos quedan frágiles.'; alcance=@('Corregir DDL de campaigns/campaign_leads/leads/lead_scores/opt_outs','Agregar índices para filtros frecuentes (phone, status, campaign_id, score)','Migración incremental sin downtime'); deps=@('D1'); desbloquea=@('K1','L2','F2'); archivos=@('scripts/campaigns-schema.sql','scripts/init-db.sql'); checks=@('DATABASE-VALIDATION sin gaps críticos','EXPLAIN de consultas clave usa índices'); refs=@('ROADMAP-IMPLEMENTACION §2.6 D2','docs/DATABASE-VALIDATION.md'); kpi='0 violaciones de integridad'; origen='Investigación D2 (P0)' }

Add-Issue @{ prefix='TASK'; id='D9'; title='Normalización de datos en ingreso (teléfono, email, mayúsculas)'; priority='high'; status='backlog'; type='task'; area='data'; milestone='Oleada 0 - Cimientos de datos'; contexto='El sanitizer cubre seguridad (23 patrones) pero no normalización de dominio: teléfonos con formatos distintos generan duplicados.'; alcance=@('Extender middleware con normalización E.164 para teléfonos','Email lowercase + trim en todo ingreso','Aplicar en POST/PATCH leads, import y webhooks'); deps=@(); desbloquea=@('K1','K13','agrupador F2'); archivos=@('helper-node/middleware/sanitizer.js','helper-node/index.js (leads/import/webhooks)'); checks=@('Test: 10 formatos de teléfono -> 1 forma canónica','Test: email con mayúsculas/espacios -> lowercase'); refs=@('ROADMAP-IMPLEMENTACION §2.6 D9','ANALISIS-CRUZADO §9.6 D9'); kpi='100% de teléfonos/emails normalizados al ingreso'; origen='Investigación D9 (P1)' }

Add-Issue @{ prefix='TASK'; id='D11'; title='Archivar conversaciones de Redis a PostgreSQL antes del TTL'; priority='critical'; status='backlog'; type='task'; area='data'; milestone='Oleada 0 - Cimientos de datos'; contexto='Las conversaciones viven en Redis con TTL 7d; el agrupador de contactos (F2) y la timeline (K7) necesitan ese historial en PG.'; alcance=@('Tabla conversations particionada por mes','Job que archiva conversaciones antes de expirar TTL','Consulta de historial por lead para agrupador y timeline'); deps=@('D1'); desbloquea=@('K12 (agrupador)','K7 (timeline)','F2/F3'); archivos=@('helper-node/services/conversationStore.js','scripts/init-db.sql'); checks=@('Conversación simulada aparece en PG tras job','Agrupador puede leer historial completo'); refs=@('ROADMAP-IMPLEMENTACION §2.6 D11','DATA-MASTER §4'); kpi='>99% de conversaciones archivadas antes de expirar'; origen='Investigación D11 (P2)' }

Add-Issue @{ prefix='TASK'; id='K9'; title='Normalización de teléfonos a nivel de base completa'; priority='medium'; status='backlog'; type='task'; area='contacts'; milestone='Oleada 0 - Cimientos de datos'; contexto='Hoy los teléfonos solo se normalizan al sincronizar a Twenty; la base propia mantiene formatos heterogéneos.'; alcance=@('Job de retro-normalización de leads existentes','Mantenimiento en toda escritura (ya cubierto por D9)','Reporte de resultados (cuántos cambiaron)'); deps=@('D9'); desbloquea=@('K1','C1'); archivos=@('helper-node/services/store.js','helper-node/index.js'); checks=@('Job sobre seed normaliza el 100%','Sin pérdida de correspondencia lead-delivery'); refs=@('ROADMAP-IMPLEMENTACION §2.2 K9'); kpi='100% teléfonos en formato canónico'; origen='Investigación K9 (P2)' }

Add-Issue @{ prefix='VERIFICATION'; id='O0'; title='Cierre Oleada 0 - verificación de cimientos'; priority='high'; status='backlog'; type='task'; area='consolidation'; milestone='Oleada 0 - Cimientos de datos'; contexto='Gate de la oleada: sin cimientos verdes no se inicia la Oleada 1 (regla de oro del proyecto).'; alcance=@('Ejecutar suite Jest completa','Ejecutar smoke + TeVS','Verificar cutover PG en runtime con dual-write','Actualizar Avances/ESTADO-GENERAL.md con resultados'); deps=@('D1','D2','D9','D11','K9'); desbloquea=@('Oleada 1'); archivos=@('Avances/ESTADO-GENERAL.md','docs/PRUEBAS-Y-VERIFICACIONES.md'); checks=@('Todos los checks de D1/D2/D9/D11/K9 en verde','Documentación de estado actualizada'); refs=@('ROADMAP-IMPLEMENTACION §4 Oleada 0, §5'); kpi='Suite completa verde'; origen='Gate de oleada (estándar del proyecto)' }

# ═══════════════════════ OLEADA 1 ═══════════════════════
Add-Issue @{ prefix='FEATURE'; id='F1'; title='Ciclo de vida del lead con etapas claras (idea de usuario)'; priority='critical'; status='backlog'; type='feature'; area='leads'; milestone='Oleada 1 - Ciclo de vida del lead (F1)'; roadmap=@('f1'); contexto='Reemplazar el lenguaje de score (Caliente/Tibio/Frío) por 6 etapas claras: Primer contacto -> Primer mensaje -> Interesado -> Cotización pendiente -> Posible comprador -> Comprador (+ Descartado/Opt-out). El score pasa a métrica de apoyo.'; alcance=@('Catálogo lead_stages configurable por tenant','Motor de transiciones validadas + historial lead_stage_history','Migración de status legados (mapeo de sinónimos existente en pipeline/page.tsx)','UI: kanban renombrado, selector de etapa, filtro por etapa','Trazabilidad en audit_logs por cada cambio (actor: agente/operador/IA)'); deps=@('D1','D2'); desbloquea=@('F2','F3','F4','C3','C6','L5','A9'); archivos=@('helper-node/index.js (leads :1384-1488)','frontend/src/app/pipeline/page.tsx','frontend/src/app/leads/page.tsx','scripts/init-db.sql (lead_stages)'); checks=@('Test transiciones válidas/inválidas (leadStages.test.js)','E2E kanban drag&drop con transición inválida rechazada','Migración de seed: 100% leads con etapa válida y trazable'); refs=@('ROADMAP-ITERATIVO-NUEVAS-FUNCIONALIDADES.md §3.1 F1','ROADMAP-IMPLEMENTACION §4 Oleada 1'); kpi='100% leads con etapa válida; 0 transiciones inválidas'; origen='Idea de usuario F1 + investigación L4/D3' }

Add-Issue @{ prefix='FEATURE'; id='L4'; title='Workflow lead -> oportunidad -> deals con conversión (parte local)'; priority='high'; status='backlog'; type='feature'; area='leads'; milestone='Oleada 1 - Ciclo de vida del lead (F1)'; roadmap=@('f1'); contexto='Los estados comerciales derivados del grafo (commercialState.js) deben reflejarse en la etapa del lead; la conversión a oportunidades de Twenty queda pospuesta (depende de I1).'; alcance=@('Hook: transición de máquina -> actualización de etapa del lead','Regla de proyección commercialState -> lead_stages','Campos SPICED/MEDDIC preparados en lead (custom_fields metodológicos)'); deps=@('F1'); desbloquea=@('C10','F3'); archivos=@('helper-node/services/agentCore/commercialState.js','helper-node/services/leadProfile.js'); checks=@('Conversación que llega a closing actualiza etapa del lead a posible_comprador/comprador','Evento en audit_logs con motivo'); refs=@('ANALISIS-CRUZADO §9.3 L4','ROADMAP-IMPLEMENTACION §2.3'); kpi='Sincronización máquina<->etapa en 100% de conversaciones'; origen='Investigación L4 (P1)' }

Add-Issue @{ prefix='FEATURE'; id='L5'; title='Score decay por inactividad'; priority='high'; status='backlog'; type='feature'; area='leads'; milestone='Oleada 1 - Ciclo de vida del lead (F1)'; contexto='Hoy la recencia es una regla estática; se necesita decadencia continua para que leads inactivos bajen prioridad y lleguen a Descartado.'; alcance=@('Job diario de decay según días sin contacto','Umbral de descarte: score < X y cadencia agotada -> etapa Descartado','Configuración por tenant'); deps=@('F1'); desbloquea=@('C4 (reactivación)','L10'); archivos=@('helper-node/index.js (scoring :1064-1186)','scripts/init-db.sql'); checks=@('Test: lead 30 días sin contacto pierde puntos según regla','Test: descarte automático tras umbral'); refs=@('ANALISIS-CRUZADO §9.3 L5','ROADMAP-IMPLEMENTACION §2.3'); kpi='Decay aplicado diariamente al 100% de leads'; origen='Investigación L5 (P1)' }

Add-Issue @{ prefix='FEATURE'; id='L8'; title='Factores del score desglosados y visibles en la UI'; priority='high'; status='backlog'; type='feature'; area='leads'; milestone='Oleada 1 - Ciclo de vida del lead (F1)'; contexto='El operador ve el número y la categoría pero no el porqué; el detalle debe mostrar los factores (+20 respondió, +15 click, -100 opt-out).'; alcance=@('UI de desglose de score_factors en detalle del lead','Tooltip explicativo por factor','Incluir modelo (reglas/LLM) y fecha'); deps=@(); desbloquea=@('L14 (feedback)'); archivos=@('frontend/src/app/leads/page.tsx (historial :208-220)','helper-node/services/leadProfile.js'); checks=@('E2E: detalle muestra factores y suma correcta','Snapshot actualizado'); refs=@('ANALISIS-CRUZADO §9.3 L8','ROADMAP-IMPLEMENTACION §2.3'); kpi='100% de scores con desglose visible'; origen='Investigación L8 (P1)' }

Add-Issue @{ prefix='FEATURE'; id='D3'; title='Pipeline configurable por tipo de cliente'; priority='high'; status='backlog'; type='feature'; area='leads'; milestone='Oleada 1 - Ciclo de vida del lead (F1)'; contexto='El kanban es un solo pipeline fijo; distintos negocios necesitan columnas propias (B2C WhatsApp / B2B / retail).'; alcance=@('Columnas del pipeline leídas de configuración (no constantes)','Config por tenant con etapas default F1','UI consume configuración'); deps=@('F1'); desbloquea=@('F3','K10'); archivos=@('frontend/src/app/pipeline/page.tsx (STAGES :11-17)','scripts/init-db.sql'); checks=@('Pipeline con columnas custom se renderiza desde config','Sin regresiones en pipeline default'); refs=@('ANALISIS-CRUZADO §9.6 D3','ROADMAP-IMPLEMENTACION §2.6'); kpi='1 pipeline configurable por tenant'; origen='Investigación D3 (P0)' }

Add-Issue @{ prefix='FEATURE'; id='K1'; title='Deduplicación con merge programado'; priority='critical'; status='backlog'; type='feature'; area='contacts'; milestone='Oleada 1 - Ciclo de vida del lead (F1)'; contexto='Solo hay dedup por teléfono al importar; faltan job programado y reglas de fusión para una base limpia.'; alcance=@('Job de detección (teléfono+email+nombre normalizados)','Reglas de ganador de campos en merge','Merge preserva scores, entregas y notas','Reporte de duplicados fusionados'); deps=@('D9','K9','D2'); desbloquea=@('C1','F2'); archivos=@('helper-node/index.js (leads)','scripts/init-db.sql'); checks=@('Test: 2 leads iguales -> 1 conservando score mayor y uniendo notas','Job sobre seed sin pérdidas'); refs=@('ANALISIS-CRUZADO §9.2 K1','ROADMAP-IMPLEMENTACION §2.2'); kpi='0 duplicados por teléfono/email'; origen='Investigación K1 (P0)' }

Add-Issue @{ prefix='VALIDATION'; id='K5'; title='Perfil 360° en UI: completar con Twenty y campañas'; priority='medium'; status='ready'; type='validation'; area='contacts'; milestone='Oleada 1 - Ciclo de vida del lead (F1)'; contexto='El perfil 360° ya existe (buildLeadProfile + detalle con notas, entregas, historial de score y mini-chat). Falta exponer datos de Twenty y campañas asociadas en la misma vista.'; alcance=@('Añadir sección Twenty (datos sincronizados) al detalle','Añadir campañas donde participó el lead','Validar visual en mobile 375 (patrón e2e existente)'); deps=@(); desbloquea=@('K7'); archivos=@('frontend/src/app/leads/page.tsx (LeadDetail :27-290)','helper-node/services/leadProfile.js'); checks=@('E2E: detalle muestra secciones Twenty/campañas cuando hay datos','Screenshot mobile sin regresiones'); refs=@('ANALISIS-CRUZADO §9.2 K5','ROADMAP-IMPLEMENTACION §2.2'); kpi='Vista 360 completa en UI'; origen='Investigación K5 (P1) - ya implementado en gran parte' }

Add-Issue @{ prefix='FEATURE'; id='K6'; title='Favoritos y notas rápidas por contacto'; priority='high'; status='backlog'; type='feature'; area='contacts'; milestone='Oleada 1 - Ciclo de vida del lead (F1)'; contexto='Las notas ya existen; falta marcar favoritos para acceso rápido del operador.'; alcance=@('Campo is_favorite + toggle en UI','Filtro "Favoritos" en leads','Ordenamiento por favorito en búsqueda'); deps=@(); desbloquea=@(); archivos=@('helper-node/index.js (PATCH leads :1450-1472)','frontend/src/app/leads/page.tsx'); checks=@('Test toggle favorito persiste','E2E filtro favoritos'); refs=@('ANALISIS-CRUZADO §9.2 K6'); kpi='Operador encuentra favoritos en 1 clic'; origen='Investigación K6 (P1)' }

Add-Issue @{ prefix='FEATURE'; id='K7'; title='Línea de tiempo unificada por contacto'; priority='high'; status='backlog'; type='feature'; area='contacts'; milestone='Oleada 1 - Ciclo de vida del lead (F1)'; contexto='Mensajes, campañas, scores y cambios de etapa viven separados; unificar en una sola timeline por contacto.'; alcance=@('Endpoint timeline: mensajes+campañas+etapas+scores+notas ordenados','UI de timeline en el detalle','Requiere D11 (historial de conversaciones en PG)'); deps=@('D11','F1'); desbloquea=@('A1','F2 (contexto del agrupador)'); archivos=@('helper-node/services/leadProfile.js','frontend/src/app/leads/page.tsx'); checks=@('Test: timeline ordenada y completa para seed','E2E visual'); refs=@('ANALISIS-CRUZADO §9.2 K7','ROADMAP-IMPLEMENTACION §2.2'); kpi='100% de interacciones en una sola vista'; origen='Investigación K7 (P1)' }

Add-Issue @{ prefix='FEATURE'; id='K13'; title='Detección de duplicados en vivo al crear/editar lead'; priority='medium'; status='backlog'; type='feature'; area='contacts'; milestone='Oleada 1 - Ciclo de vida del lead (F1)'; contexto='Sugerir contactos existentes mientras el operador escribe evita duplicados desde el origen.'; alcance=@('Sugerencia en formulario de creación (match parcial nombre/teléfono)','Acción "usar existente" que evita crear','Consume /api/leads/search'); deps=@('D9'); desbloquea=@(); archivos=@('frontend/src/app/pipeline/page.tsx (crear lead :278-309)','helper-node/index.js (search :1436)'); checks=@('E2E: escribir teléfono existente muestra sugerencia'); refs=@('ANALISIS-CRUZADO §9.2 K13'); kpi='Reducción de duplicados en creación'; origen='Investigación K13 (P3)' }

Add-Issue @{ prefix='VERIFICATION'; id='O1'; title='Cierre Oleada 1 - validación del ciclo de vida'; priority='high'; status='backlog'; type='task'; area='consolidation'; milestone='Oleada 1 - Ciclo de vida del lead (F1)'; contexto='Gate de oleada: etapas, dedup y timeline deben quedar verificados antes de grupos/segmentos.'; alcance=@('Suite Jest + e2e del kanban','Verificación de migración de etapas sobre seed','Actualizar Avances/ y MAESTRO-FUNCIONALIDADES-CORE'); deps=@('F1','L4','L5','L8','D3','K1','K5','K6','K7','K13'); desbloquea=@('Oleada 2'); archivos=@('Avances/ESTADO-GENERAL.md','docs/maestro/MAESTRO-FUNCIONALIDADES-CORE.md'); checks=@('Todos los DoD de la oleada en verde','Docs actualizadas'); refs=@('ROADMAP-IMPLEMENTACION §4 Oleada 1'); kpi='Oleada 1 100% verde'; origen='Gate de oleada' }

# ═══════════════════════ OLEADA 2 ═══════════════════════
Add-Issue @{ prefix='FEATURE'; id='F2'; title='Grupos de contactos manuales + agrupador IA (idea de usuario)'; priority='high'; status='backlog'; type='feature'; area='contacts'; milestone='Oleada 2 - Grupos y segmentos (F2/F3)'; roadmap=@('f2'); contexto='El operador crea grupos con criterio en lenguaje natural (ej. teclados, pantallas) y un agrupador IA revisa todos los leads con conversación y los asigna. El patrón ya existe en chatGroups.js (sobre conversaciones).'; alcance=@('Tabla lead_groups + vínculo N:M lead_group_members','CRUD de grupos con name/description/criteria/color','Agrupador batch: clasifica leads con conversación (LLM + fallback heurístico, concurrencia limitada)','Grupo sistema "Sin agrupar"','UI de grupos en /leads con botón "Ejecutar agrupador" + progreso + resumen','Asignación con source/confidence/reasoning auditable'); deps=@('D11','F1','K12'); desbloquea=@('F3','C3','F4 (cards por grupo)','E (audiencia)'); archivos=@('helper-node/services/chatGroups.js (patrón a reutilizar)','helper-node/services/agentCore/llmClient.js (classifyIntoGroup)','frontend/src/app/leads/page.tsx'); checks=@('Test leadGroups.test.js: CRUD + asignación manual/IA','Batch sobre seed: 100% con grupo o Sin agrupar','Acierto >=80% validado con feedback'); refs=@('ROADMAP-ITERATIVO-NUEVAS-FUNCIONALIDADES.md §3.2 F2','ANALISIS-CRUZADO K4/K12/C3'); kpi='>=95% de leads con conversación agrupados'; origen='Idea de usuario F2 + investigación K12/K4' }

Add-Issue @{ prefix='FEATURE'; id='F3'; title='Segmentación activa por agente según lógica de negocio (idea de usuario)'; priority='high'; status='backlog'; type='feature'; area='leads'; milestone='Oleada 2 - Grupos y segmentos (F2/F3)'; roadmap=@('f3'); contexto='La IA propone 4-5 grupos fijos según la lógica del negocio (rango de compras, consultas, compras) y mantiene la clasificación viva; las campañas consumen estos segmentos para bajar el costo de personalización.'; alcance=@('Segmentos dinámicos: kind=dynamic con reglas evaluables (etapa, score, recencia, replies)','Sugerencia de segmentos por IA desde plantilla de negocio + KB (aprobación del operador)','Job continuo de re-clasificación (L2)','Señales proxy MVP (montos reales = Frappe, diferido)'); deps=@('F2','F1','L6'); desbloquea=@('C3','C4','C6','F5'); archivos=@('helper-node/services/agentCore/commercialState.js','scripts/init-db.sql (lead_groups kind/rules)','frontend/src/app/leads/page.tsx'); checks=@('Recalculo de segmentos < 1h tras cambio de reglas','Sugerencia IA genera 4-5 segmentos coherentes con la plantilla','Test segmentos.test.js'); refs=@('ROADMAP-ITERATIVO-NUEVAS-FUNCIONALIDADES.md §3.3 F3','ANALISIS-CRUZADO C3/L2/L6'); kpi='Ahorro >=40% tokens en personalización por segmento'; origen='Idea de usuario F3 + investigación C3' }

Add-Issue @{ prefix='FEATURE'; id='K4'; title='Tags multi-valor con colores por lead'; priority='high'; status='backlog'; type='feature'; area='contacts'; milestone='Oleada 2 - Grupos y segmentos (F2/F3)'; contexto='Etiquetas visuales complementarias a los grupos para clasificación libre del operador.'; alcance=@('Campo tags[] en lead + CRUD de tags con color','UI de tags en detalle y listado','Filtro por tag en leads'); deps=@(); desbloquea=@('F3 (reglas por tag)'); archivos=@('helper-node/index.js (leads)','frontend/src/lib/format.ts (GROUP_COLORS :92-111)'); checks=@('Test CRUD tags','E2E filtrar por tag'); refs=@('ANALISIS-CRUZADO §9.2 K4'); kpi='Tags visibles y filtrables'; origen='Investigación K4 (P1)' }

Add-Issue @{ prefix='FEATURE'; id='K10'; title='Campos custom configurables por tenant desde UI'; priority='medium'; status='backlog'; type='feature'; area='contacts'; milestone='Oleada 2 - Grupos y segmentos (F2/F3)'; contexto='custom_fields JSONB existe pero sin editor; los criterios de grupos/segmentos deben poder referirse a campos propios del negocio.'; alcance=@('Editor UI de campos custom (nombre, tipo, requerido)','Almacenamiento por tenant','Uso en criterios de segmentos y en el form de lead'); deps=@('F1'); desbloquea=@('F3'); archivos=@('helper-node/index.js','frontend/src/app/settings/page.tsx'); checks=@('E2E: crear campo custom y usarlo en filtro'); refs=@('ANALISIS-CRUZADO §9.2 K10'); kpi='Campos custom sin tocar código'; origen='Investigación K10 (P2)' }

Add-Issue @{ prefix='FEATURE'; id='K12'; title='Listas manuales de leads (grupos fijos)'; priority='high'; status='backlog'; type='feature'; area='contacts'; milestone='Oleada 2 - Grupos y segmentos (F2/F3)'; roadmap=@('f2'); contexto='Componente núcleo de F2: grupos manuales sobre la entidad lead (hoy chatGroups opera sobre conversaciones).'; alcance=@('Modelo lead_groups manual','Asignación manual de leads a grupos (UI)','Persistencia y auditoría'); deps=@('D1'); desbloquea=@('F2','C3'); archivos=@('helper-node/services/chatGroups.js (reutilizar)','scripts/init-db.sql'); checks=@('Test asignación manual y desasignación'); refs=@('ANALISIS-CRUZADO §9.2 K12','ROADMAP-IMPLEMENTACION §2.2'); kpi='Grupos manuales operativos'; origen='Investigación K12 (P2)' }

Add-Issue @{ prefix='FEATURE'; id='L2'; title='Recalificación automática periódica de leads'; priority='critical'; status='backlog'; type='feature'; area='leads'; milestone='Oleada 2 - Grupos y segmentos (F2/F3)'; contexto='evaluate-all existe pero es manual (botón Score All); se necesita job programado para scores siempre frescos y para alimentar segmentos dinámicos.'; alcance=@('Job diario que re-evalúa todos los leads','Detección de reglas cambiadas -> re-evaluación forzada','Log de corrida en audit_logs'); deps=@(); desbloquea=@('F3','L5'); archivos=@('helper-node/index.js (evaluate-all :1186)','n8n/workflows/ (o cron interno)'); checks=@('Job diario verificado en logs','Scores actualizados tras cambio de reglas'); refs=@('ANALISIS-CRUZADO §9.3 L2','ROADMAP-IMPLEMENTACION §2.3'); kpi='100% de leads re-evaluados cada 24h'; origen='Investigación L2 (P0)' }

Add-Issue @{ prefix='FEATURE'; id='L6'; title='Ponderación de scoring por rubro (plantilla de negocio)'; priority='high'; status='backlog'; type='feature'; area='leads'; milestone='Oleada 2 - Grupos y segmentos (F2/F3)'; contexto='Las plantillas por rubro ya definen objeciones y follow-up; falta que definan pesos de scoring (qué señales importan más por negocio).'; alcance=@('Campo scoring.weights en templates/*.json','Motor de reglas consume pesos por plantilla activa','UI de ajuste en settings'); deps=@('F1'); desbloquea=@('F3','L11'); archivos=@('helper-node/templates/template-consultora-software.json','helper-node/services/templateEngine.js','helper-node/index.js (scoring rules :1064)'); checks=@('Test: mismo lead con 2 plantillas da scores distintos según pesos'); refs=@('ANALISIS-CRUZADO §9.3 L6','CTX-05'); kpi='Pesos por rubro activos'; origen='Investigación L6 (P1)' }

Add-Issue @{ prefix='FEATURE'; id='C3'; title='Segmentos dinámicos como fuente de audiencia'; priority='critical'; status='backlog'; type='feature'; area='campaigns'; milestone='Oleada 2 - Grupos y segmentos (F2/F3)'; roadmap=@('f3'); contexto='Las campañas hoy seleccionan audiencia por listas manuales o todo; con F2/F3 listos, la audiencia debe resolverse desde grupos/segmentos.'; alcance=@('Definición de reglas de segmento evaluables','Endpoint de resolución de audiencia (segmento -> leads)','Cache de audiencia resuelta'); deps=@('F3','K12'); desbloquea=@('C4','C6','C9','Oleada 3'); archivos=@('helper-node/index.js (broadcast :3005-3058)','scripts/init-db.sql'); checks=@('Test: segmento "score>=70" resuelve la lista esperada','Audiencia consistente entre dry-run y envío'); refs=@('ANALISIS-CRUZADO §9.1 C3','ROADMAP-IMPLEMENTACION §2.1'); kpi='>=50% de campañas con audiencia por segmento'; origen='Investigación C3 (P0)' }

Add-Issue @{ prefix='VERIFICATION'; id='O2'; title='Cierre Oleada 2 - validación de grupos y segmentos'; priority='high'; status='backlog'; type='task'; area='consolidation'; milestone='Oleada 2 - Grupos y segmentos (F2/F3)'; contexto='Gate: segmentación viva y validada antes de campañas segmentadas.'; alcance=@('Batch agrupador sobre seed con métricas de acierto','Recalculo de segmentos verificado','Actualizar docs'); deps=@('F2','F3','K4','K10','K12','L2','L6','C3'); desbloquea=@('Oleada 3'); archivos=@('Avances/ESTADO-GENERAL.md'); checks=@('Todos los DoD de la oleada en verde'); refs=@('ROADMAP-IMPLEMENTACION §4 Oleada 2'); kpi='Oleada 2 100% verde'; origen='Gate de oleada' }

# ═══════════════════════ OLEADA 3 ═══════════════════════
Add-Issue @{ prefix='FEATURE'; id='C1'; title='Bloquear envíos a leads opt-out en el motor de campañas'; priority='critical'; status='backlog'; type='feature'; area='campaigns'; milestone='Oleada 3 - Campañas inteligentes'; contexto='El registro de opt-out existe (STOP -> opted_out) y el broadcast filtra, pero el motor de envío de campañas no consulta opt-outs en su loop. Cumplimiento y reputación de canal.'; alcance=@('Consulta de opt-outs en cada envío del loop','Exclusión de opted_out al resolver audiencia (start/programación)','Log envio_bloqueado_optout en audit_logs'); deps=@('K9'); desbloquea=@('C4','C6'); archivos=@('helper-node/index.js (motor de envío :244-378, check-batch :1311)','n8n/workflows/02-campaign-broadcast.json'); checks=@('Test: lead opt-out -> 0 envíos y log de bloqueo','E2E: STOP -> campaña posterior no le envía'); refs=@('ANALISIS-CRUZADO §9.1 C1','ROADMAP-IMPLEMENTACION §2.1'); kpi='0 envíos a opt-outs'; origen='Investigación C1 (P0)' }

Add-Issue @{ prefix='FEATURE'; id='C4'; title='Campañas de reactivación automáticas'; priority='high'; status='backlog'; type='feature'; area='campaigns'; milestone='Oleada 3 - Campañas inteligentes'; contexto='Leads tibios que no respondieron en N días reciben mensaje de reactivación automáticamente (GoHighLevel database reactivation).'; alcance=@('Tipo de campaña reactivación con regla de audiencia (score>=warm + días sin respuesta)','Activación manual y programada','Plantilla por defecto de reactivación'); deps=@('C3','C1'); desbloquea=@(); archivos=@('helper-node/index.js (campañas)','frontend/src/app/campaigns/page.tsx'); checks=@('Test: audiencia de reactivación coincide con regla','E2E crear reactivación y ver audiencia'); refs=@('ANALISIS-CRUZADO §9.1 C4'); kpi='Reactivaciones sin trabajo manual'; origen='Investigación C4 (P1)' }

Add-Issue @{ prefix='FEATURE'; id='C5'; title='A/B testing de plantillas en campañas'; priority='high'; status='backlog'; type='feature'; area='campaigns'; milestone='Oleada 3 - Campañas inteligentes'; contexto='Probar dos variantes sobre mitades de la audiencia y medir cuál responde mejor.'; alcance=@('Campo variantes[] en campaña con split de audiencia','Métricas por variante (sent/replied)','Reporte de ganadora'); deps=@('C3'); desbloquea=@('L11'); archivos=@('helper-node/index.js (campañas :244-378)','frontend/src/app/campaigns/page.tsx'); checks=@('Test: split 50/50 consistente y determinístico','E2E: métricas separadas por variante'); refs=@('ANALISIS-CRUZADO §9.1 C5'); kpi='>=1 campaña A/B mensual medible'; origen='Investigación C5 (P1)' }

Add-Issue @{ prefix='FEATURE'; id='C6'; title='Campañas por evento de fecha (aniversario, post-compra)'; priority='high'; status='backlog'; type='feature'; area='campaigns'; milestone='Oleada 3 - Campañas inteligentes'; contexto='Triggers por fechas del contacto; MVP: fecha configurable por lead (cumpleaños si existe el campo); post-compra requiere Frappe (diferido).'; alcance=@('Regla de trigger por campo fecha','Job que detecta eventos del día y dispara campaña','MVP con campo custom fecha'); deps=@('C3','K10'); desbloquea=@(); archivos=@('helper-node/index.js','scripts/init-db.sql'); checks=@('Test: trigger de fecha dispara campaña correcta'); refs=@('ANALISIS-CRUZADO §9.1 C6'); kpi='Campañas por evento automáticas'; origen='Investigación C6 (P1)' }

Add-Issue @{ prefix='FEATURE'; id='C8'; title='Rate-limit inteligente por canal con backoff y re-intentos'; priority='high'; status='backlog'; type='feature'; area='campaigns'; milestone='Oleada 3 - Campañas inteligentes'; contexto='Hoy solo se informa el límite; el envío debe esperar y reintentar para no ser bloqueado por los canales.'; alcance=@('Backoff exponencial respetando rate_limit_reset_at','Re-intentos con máx configurable','Métricas de retries por campaña'); deps=@(); desbloquea=@(); archivos=@('helper-node/index.js (channels :981-1014)','helper-node/services/channels/*'); checks=@('Test: simular rate-limit -> espera y reintenta','Log de backoff en audit_logs'); refs=@('ANALISIS-CRUZADO §9.1 C8'); kpi='Envíos sin bloqueos por límite'; origen='Investigación C8 (P1)' }

Add-Issue @{ prefix='FEATURE'; id='C9'; title='Dry-run de campaña: simular audiencia y costo antes de enviar'; priority='medium'; status='backlog'; type='feature'; area='campaigns'; milestone='Oleada 3 - Campañas inteligentes'; contexto='Previsualizar audiencia resuelta, conteo y costo estimado con confirmación visual antes de lanzar.'; alcance=@('Endpoint dry-run que resuelve audiencia sin enviar','UI de confirmación con conteo y costo estimado','Bloqueo de envío si el dry-run no fue confirmado'); deps=@('C3'); desbloquea=@(); archivos=@('helper-node/index.js (campañas)','frontend/src/app/campaigns/page.tsx'); checks=@('E2E: dry-run muestra conteo exacto antes de envío'); refs=@('ANALISIS-CRUZADO §9.1 C9'); kpi='0 envíos sin dry-run confirmado'; origen='Investigación C9 (P2)' }

Add-Issue @{ prefix='FEATURE'; id='C10'; title='Atribución MVP campaña -> respuestas -> etapas avanzadas'; priority='medium'; status='backlog'; type='feature'; area='campaigns'; milestone='Oleada 3 - Campañas inteligentes'; contexto='Stats por campaña existen; falta enlazar a resultados de negocio. ROI de ventas real queda diferido a Frappe.'; alcance=@('Reporte: campaña -> replies -> leads que avanzaron etapa','Tabla de atribución en el detalle de campaña','Extensión a ventas cuando Frappe exista (diferido)'); deps=@('F1','C3'); desbloquea=@('L7'); archivos=@('helper-node/index.js (stats :755-768)','frontend/src/app/campaigns/page.tsx'); checks=@('Test: atribución correcta sobre dataset sintético'); refs=@('ANALISIS-CRUZADO §9.1 C10','ROADMAP-IMPLEMENTACION §2.1'); kpi='Atribución visible por campaña'; origen='Investigación C10 (P2)' }

Add-Issue @{ prefix='FEATURE'; id='C12'; title='Validación de plantillas por canal (HSM vs sesión)'; priority='medium'; status='backlog'; type='feature'; area='campaigns'; milestone='Oleada 3 - Campañas inteligentes'; contexto='El sistema debe distinguir mensajes que requieren plantilla aprobada por Meta de los libres, sin depender aún de credenciales reales (C2 no seleccionada).'; alcance=@('Flag en plantilla: requires_approval por canal','Validación en el form de campaña con aviso','max_length ya existente se mantiene'); deps=@(); desbloquea=@('F5'); archivos=@('helper-node/index.js (templates :1782-1945)','frontend/src/app/campaigns/page.tsx','frontend/src/app/templates/page.tsx'); checks=@('Test: plantilla HSM marcada rechaza envío directo fuera de sesión (simulado)'); refs=@('ANALISIS-CRUZADO §9.1 C12'); kpi='0 envíos con plantilla no válida para el canal'; origen='Investigación C12 (P2)' }

Add-Issue @{ prefix='VERIFICATION'; id='O3'; title='Cierre Oleada 3 - validación de campañas inteligentes'; priority='high'; status='backlog'; type='task'; area='consolidation'; milestone='Oleada 3 - Campañas inteligentes'; contexto='Gate: campañas segmentadas, verificables y sin envíos indebidos.'; alcance=@('E2E campaña a segmento + bloqueo opt-out + dry-run','Métricas de ahorro de tokens (segmento vs por-lead)','Actualizar docs'); deps=@('C1','C4','C5','C6','C8','C9','C10','C12'); desbloquea=@('Oleada 4'); archivos=@('Avances/ESTADO-GENERAL.md'); checks=@('Todos los DoD de la oleada en verde'); refs=@('ROADMAP-IMPLEMENTACION §4 Oleada 3'); kpi='Oleada 3 100% verde'; origen='Gate de oleada' }

# ═══════════════════════ OLEADA 4 ═══════════════════════
Add-Issue @{ prefix='VALIDATION'; id='R2'; title='Grafo comercial de 8+ etapas: validación integral'; priority='high'; status='ready'; type='validation'; area='responses'; milestone='Oleada 4 - Respuestas automáticas'; contexto='El grafo comercial ya está IMPLEMENTADO y activo en el inbound multicanal (11 nodos, aristas condicionales, checkpointer, guards). La investigación lo marcaba pendiente; el código demuestra lo contrario. NO requiere desarrollo nuevo: validar y documentar.'; alcance=@('E2E integral: apertura -> calificación -> propuesta -> objeciones -> cierre/handoff','Cobertura de los 11 nodos en pruebas','Documentar estado real en TEC-02/MAESTRO','Exponer traza de etapas en la UI de conversación'); deps=@(); desbloquea=@('R6','A5','F4'); archivos=@('helper-node/services/agentCore/index.js (:76-267)','helper-node/services/agentCore/nodes/*','helper-node/__tests__/agentGraph.test.js','e2e/specs/flow-simulations.spec.js'); checks=@('E2E de todos los flujos del grafo en verde','Docs actualizadas con el estado real (implementado)'); refs=@('ANALISIS-CRUZADO §9.4 R2','ROADMAP-IMPLEMENTACION §2.4'); kpi='100% de flujos del grafo cubiertos por e2e'; origen='Investigación R2 (P0) - YA IMPLEMENTADO en código' }

Add-Issue @{ prefix='VALIDATION'; id='R15'; title='Simulador de conversación: exponer en UI settings'; priority='medium'; status='ready'; type='validation'; area='responses'; milestone='Oleada 4 - Respuestas automáticas'; contexto='El simulador existe (agentCore/testGraph.js + /api/agent/test-graph + spec flow-simulations). Falta exponerlo al operador en la UI de settings.'; alcance=@('Botón "Probar agente" en settings (usa testGraph)','Mostrar ruta de nodos y respuesta simulada','Mantener spec e2e existente'); deps=@(); desbloquea=@(); archivos=@('helper-node/services/agentCore/testGraph.js','helper-node/index.js (:380 test-graph)','frontend/src/app/settings/page.tsx'); checks=@('E2E: probar agente desde settings muestra resultado'); refs=@('ANALISIS-CRUZADO §9.4 R15','ROADMAP-IMPLEMENTACION §2.4'); kpi='Simulador accesible desde UI'; origen='Investigación R15 (P3) - YA IMPLEMENTADO en código' }

Add-Issue @{ prefix='FEATURE'; id='R1'; title='Bienvenida y fuera de horario configurables por tenant'; priority='critical'; status='backlog'; type='feature'; area='responses'; milestone='Oleada 4 - Respuestas automáticas'; contexto='Existe plantilla de bienvenida y greeting en config de agente; falta mensaje fuera de horario con horario configurable.'; alcance=@('Config de horario de atención por tenant','Respuesta automática fuera de horario','Plantilla configurable'); deps=@(); desbloquea=@(); archivos=@('helper-node/services/agentConfig.js','frontend/src/app/settings/page.tsx (greeting :521)','helper-node/index.js (templates welcome :1784)'); checks=@('Test: mensaje fuera de horario se dispara según config','E2E en settings'); refs=@('ANALISIS-CRUZADO §9.4 R1'); kpi='0 mensajes sin respuesta fuera de horario'; origen='Investigación R1 (P0)' }

Add-Issue @{ prefix='FEATURE'; id='R4'; title='Snippets y respuestas rápidas en el chat del operador'; priority='high'; status='backlog'; type='feature'; area='responses'; milestone='Oleada 4 - Respuestas automáticas'; contexto='Textos rápidos reutilizables dentro del chat humano (Kommo quick replies).'; alcance=@('CRUD de snippets (reutilizar templates con categoría snippet)','Panel de snippets en el chat con inserción en 1 clic','Variables por lead resueltas'); deps=@(); desbloquea=@(); archivos=@('frontend/src/app/chat/page.tsx','helper-node/index.js (templates)'); checks=@('E2E: insertar snippet en el chat resuelve variables'); refs=@('ANALISIS-CRUZADO §9.4 R4'); kpi='Tiempo de respuesta del operador -20%'; origen='Investigación R4 (P1)' }

Add-Issue @{ prefix='FEATURE'; id='R5'; title='Agentes por rol con router y fallback'; priority='high'; status='backlog'; type='feature'; area='responses'; milestone='Oleada 4 - Respuestas automáticas'; contexto='agentRegistry existe; falta topología router->especialista sobre los nodos existentes con fallback.'; alcance=@('Router por intención hacia nodos especializados (reutiliza nodos del grafo)','Fallback al flujo general','Métricas por agente'); deps=@('R2'); desbloquea=@(); archivos=@('helper-node/services/agentRegistry.js','helper-node/services/agentCore/index.js'); checks=@('Test: intención soporte -> nodo KB; intención venta -> grafo'); refs=@('ANALISIS-CRUZADO §9.4 R5'); kpi='Routing por intención operativo'; origen='Investigación R5 (P1)' }

Add-Issue @{ prefix='FEATURE'; id='R6'; title='Regla de handoff inmediato cuando el cliente pide humano'; priority='high'; status='backlog'; type='feature'; area='responses'; milestone='Oleada 4 - Respuestas automáticas'; contexto='El nodo handoff y el estado escalated existen; falta la regla explícita medible y configurable.'; alcance=@('Detección "quiero hablar con una persona" -> escalated inmediato','Métrica de cumplimiento (tiempo hasta handoff)','Config on/off por tenant'); deps=@('R2'); desbloquea=@('A5','L10'); archivos=@('helper-node/services/agentCore/nodes/handoffNode.js','helper-node/services/agentCore/guards/autonomy.js'); checks=@('Test: mensaje pidiendo humano -> escalated en <1 turno','Métrica registrada en audit_logs'); refs=@('ANALISIS-CRUZADO §9.4 R6'); kpi='>=90% de handoffs pedidos cumplidos inmediatamente'; origen='Investigación R6 (P1)' }

Add-Issue @{ prefix='FEATURE'; id='R7'; title='Sincronización externa de la KB (productos, precios, horarios)'; priority='high'; status='backlog'; type='feature'; area='responses'; milestone='Oleada 4 - Respuestas automáticas'; contexto='La KB es local; el bot debe responder con datos reales del negocio traídos de una fuente externa.'; alcance=@('Contrato de sync flexible (API/file del negocio)','Job de actualización de documentos KB','Versionado y auditoría de cambios'); deps=@(); desbloquea=@('R13'); archivos=@('helper-node/services/ragEngine.js','helper-node/kb-documents/','helper-node/index.js (knowledge-base :2419-2478)'); checks=@('Test: sync actualiza documentos y query devuelve dato nuevo'); refs=@('ANALISIS-CRUZADO §9.4 R7','TEC-02 G11'); kpi='KB actualizada sin intervención manual'; origen='Investigación R7 (P1)' }

Add-Issue @{ prefix='FEATURE'; id='R8'; title='Límite de intentos y escalamiento de canal'; priority='high'; status='backlog'; type='feature'; area='responses'; milestone='Oleada 4 - Respuestas automáticas'; contexto='lost_threshold por plantilla ya existe en el nodo seguimiento; falta escalar de canal (WhatsApp -> llamada) y materializar el intento como evento.'; alcance=@('Tras lost_threshold: evento de escalamiento (canal alternativo/llamada)','Notificación al operador','Config por plantilla'); deps=@('A2'); desbloquea=@('F4'); archivos=@('helper-node/services/agentCore/nodes/followupNode.js (:7 lost_threshold)','helper-node/templates/*.json'); checks=@('Test: agotar cadencia genera evento de escalamiento'); refs=@('ANALISIS-CRUZADO §9.4 R8','CTX-04 §6'); kpi='100% de cadencias agotadas generan escalamiento'; origen='Investigación R8 (P1)' }

Add-Issue @{ prefix='FEATURE'; id='R12'; title='Autorespuestas a comandos MENU/HORARIOS/PRECIO'; priority='medium'; status='backlog'; type='feature'; area='responses'; milestone='Oleada 4 - Respuestas automáticas'; contexto='STOP ya funciona; faltan los comandos de autoservicio estándar de WhatsApp Business.'; alcance=@('Comandos configurables con respuesta rápida','Detección previa al grafo (bajo costo, sin LLM)','Registro en audit_logs'); deps=@(); desbloquea=@(); archivos=@('helper-node/index.js (webhook twilio :2568-2577)','helper-node/services/agentConfig.js'); checks=@('Test: PRECIO responde con plantilla sin llamar al LLM'); refs=@('ANALISIS-CRUZADO §9.4 R12'); kpi='Comandos respondidos <1s sin costo LLM'; origen='Investigación R12 (P2)' }

Add-Issue @{ prefix='FEATURE'; id='R13'; title='Catálogo multimedia en respuestas automáticas'; priority='medium'; status='backlog'; type='feature'; area='responses'; milestone='Oleada 4 - Respuestas automáticas'; contexto='El pipeline multimodal (STT/visión/TTS/media) ya existe; falta un catálogo simple de productos con imágenes servidas por el bot.'; alcance=@('Entidad catálogo: producto + imagen + descripción','Consulta por intención de producto -> envío de imagen','Reutiliza /api/chat/reply media'); deps=@('R7'); desbloquea=@(); archivos=@('helper-node/services/mediaProcessor.js','helper-node/index.js (chat/reply :3534-3594)','helper-node/index.js (chat/media :3514)'); checks=@('E2E: pedir producto -> recibe imagen del catálogo'); refs=@('ANALISIS-CRUZADO §9.4 R13'); kpi='Catálogo visible en conversaciones'; origen='Investigación R13 (P2)' }

Add-Issue @{ prefix='FEATURE'; id='R14'; title='Registro de opt-in explícito por lead'; priority='medium'; status='backlog'; type='feature'; area='responses'; milestone='Oleada 4 - Respuestas automáticas'; contexto='El opt-out está completo; falta el consentimiento explícito para campañas (doble registro).'; alcance=@('Campo opt_in con fecha y origen','Registro en webhook al confirmar interés','Uso en audiencias de campaña (solo opt-in)'); deps=@(); desbloquea=@('C1'); archivos=@('helper-node/index.js (opt-outs :1020-1058)','scripts/init-db.sql'); checks=@('Test: confirmación de interés marca opt_in'); refs=@('ANALISIS-CRUZADO §9.4 R14','GDPR'); kpi='100% de campañas con audiencia opt-in'; origen='Investigación R14 (P3)' }

Add-Issue @{ prefix='VERIFICATION'; id='O4'; title='Cierre Oleada 4 - validación de respuestas automáticas'; priority='high'; status='backlog'; type='task'; area='consolidation'; milestone='Oleada 4 - Respuestas automáticas'; contexto='Gate: atención automática completa y validada (incluye las dos funcionalidades ya implementadas).'; alcance=@('E2E integral del grafo + comandos + handoff','Métricas de cumplimiento de handoff','Actualizar docs con estado real de R2/R15'); deps=@('R1','R2','R4','R5','R6','R7','R8','R12','R13','R14','R15'); desbloquea=@('Oleada 5'); archivos=@('Avances/ESTADO-GENERAL.md','docs/tecnica/TEC-02'); checks=@('Todos los DoD de la oleada en verde'); refs=@('ROADMAP-IMPLEMENTACION §4 Oleada 4'); kpi='Oleada 4 100% verde'; origen='Gate de oleada' }

# ═══════════════════════ OLEADA 5 ═══════════════════════
Add-Issue @{ prefix='FEATURE'; id='A1'; title='Copiloto IA embebido en el chat del operador'; priority='critical'; status='backlog'; type='feature'; area='agents'; milestone='Oleada 5 - Copiloto y asignación'; contexto='/api/llm/chat y el perfil existen; falta el panel copiloto en el chat: resumen de conversación y sugerencia de respuesta.'; alcance=@('Panel lateral en /chat con resumen en vivo','Botón "sugerir respuesta" (usa llm/chat + perfil)','Inserción de la sugerencia con 1 clic'); deps=@('K7'); desbloquea=@(); archivos=@('frontend/src/app/chat/page.tsx','helper-node/index.js (llm/chat :2269)','helper-node/services/leadProfile.js'); checks=@('E2E: abrir conversación -> copiloto sugiere respuesta coherente'); refs=@('ANALISIS-CRUZADO §9.5 A1','ROADMAP-IMPLEMENTACION §2.5'); kpi='>=60% de respuestas del operador usan copiloto'; origen='Investigación A1 (P0)' }

Add-Issue @{ prefix='FEATURE'; id='A5'; title='Handoff HITL con contexto completo (12 campos)'; priority='high'; status='backlog'; type='feature'; area='agents'; milestone='Oleada 5 - Copiloto y asignación'; contexto='El handoffNode existe; debe entregar al operador el contexto completo del diseño CTX-04 §7 con nota de IA.'; alcance=@('Paquete de handoff con los 12 campos + nota IA','Entrega al operador asignado en la UI','Auditoría del traspaso'); deps=@('R6'); desbloquea=@(); archivos=@('helper-node/services/agentCore/nodes/handoffNode.js','frontend/src/app/chat/page.tsx','docs/contextual/CTX-04-LOGICA-VENDEDOR.md §7'); checks=@('Test: handoff incluye los 12 campos','E2E: operador recibe caso con contexto'); refs=@('ANALISIS-CRUZADO §9.5 A5','CTX-04 §7'); kpi='100% de handoffs con contexto completo'; origen='Investigación A5 (P1)' }

Add-Issue @{ prefix='FEATURE'; id='A6'; title='Asignación de conversaciones nuevas (round-robin/score)'; priority='high'; status='backlog'; type='feature'; area='agents'; milestone='Oleada 5 - Copiloto y asignación'; contexto='No existe reparto de conversaciones; base para el routing por calificación (L3).'; alcance=@('Colas por operador','Modos: round-robin / por score / manual','UI de colas en /chat'); deps=@(); desbloquea=@('L3','L10'); archivos=@('helper-node/index.js','frontend/src/app/chat/page.tsx','scripts/init-db.sql'); checks=@('Test: round-robin distribuye equitativamente','E2E: conversación nueva aparece en cola asignada'); refs=@('ANALISIS-CRUZADO §9.5 A6','ROADMAP-IMPLEMENTACION §2.5'); kpi='Reparto equitativo sin intervención'; origen='Investigación A6 (P1)' }

Add-Issue @{ prefix='FEATURE'; id='A7'; title='Resúmenes post-conversación visibles en la UI'; priority='high'; status='backlog'; type='feature'; area='agents'; milestone='Oleada 5 - Copiloto y asignación'; contexto='El briefing del grafo y conversation_summaries en PG existen; falta exponerlos para el operador y el CRM.'; alcance=@('UI: resumen al cerrar/escalar conversación','Inclusión en el handoff y en el perfil del lead','Exportable a Twenty (cuando I1 exista)'); deps=@(); desbloquea=@('A5'); archivos=@('helper-node/services/agentCore/index.js (briefing :265)','frontend/src/app/chat/page.tsx','frontend/src/app/leads/page.tsx'); checks=@('E2E: tras conversación, resumen visible en el lead'); refs=@('ANALISIS-CRUZADO §9.5 A7'); kpi='100% de conversaciones con resumen persistido'; origen='Investigación A7 (P1)' }

Add-Issue @{ prefix='VALIDATION'; id='A9'; title='Recomendación de próximo mejor paso: enriquecer'; priority='medium'; status='ready'; type='validation'; area='agents'; milestone='Oleada 5 - Copiloto y asignación'; contexto='nextAction YA EXISTE (perfil de lead + grafo) y se muestra en la UI. Falta enriquecerlo con contexto de grupos/etapas.'; alcance=@('nextAction considera etapa + grupo/segmento + score','Sugerencias accionables con enlace (enviar oferta, agendar)','Validar sobre seed'); deps=@('F1','F2'); desbloquea=@(); archivos=@('helper-node/services/leadProfile.js','frontend/src/app/leads/page.tsx (:147-154)'); checks=@('Test: nextAction cambia según etapa/grupo'); refs=@('ANALISIS-CRUZADO §9.5 A9','ROADMAP-IMPLEMENTACION §2.5'); kpi='nextAction presente en 100% de leads'; origen='Investigación A9 (P2) - YA IMPLEMENTADO en gran parte' }

Add-Issue @{ prefix='FEATURE'; id='A10'; title='Checklist de metodología de venta por etapa en la UI'; priority='medium'; status='backlog'; type='feature'; area='agents'; milestone='Oleada 5 - Copiloto y asignación'; contexto='Las metodologías SPICED/MEDDIC están en CTX-04; falta guiarlas al operador en el panel según la etapa.'; alcance=@('Panel con checklist según etapa de la conversación','Check-off manual con registro en audit_logs'); deps=@('F1'); desbloquea=@(); archivos=@('frontend/src/app/chat/page.tsx','docs/contextual/CTX-04-LOGICA-VENDEDOR.md §8'); checks=@('E2E: etapa propuesta muestra checklist SPICED'); refs=@('ANALISIS-CRUZADO §9.5 A10','CTX-04 §8'); kpi='Uso de checklist en conversaciones de venta'; origen='Investigación A10 (P2)' }

Add-Issue @{ prefix='FEATURE'; id='A11'; title='Cotización desde el chat (MVP mini-cotización)'; priority='medium'; status='backlog'; type='feature'; area='agents'; milestone='Oleada 5 - Copiloto y asignación'; contexto='quoteEngine y el nodo cotizacion YA generan mini-cotización. Falta permitir enviar el resumen por el chat y preparar el documento formal (diferido a Frappe).'; alcance=@('Envío del resumen de cotización por el chat (texto estructurado)','Registro de cotización enviada como evento (alimenta F4)','Documento formal: diferido a Frappe'); deps=@(); desbloquea=@('F4'); archivos=@('helper-node/services/agentCore/quoteEngine.js','helper-node/services/agentCore/nodes/cotizacionNode.js','frontend/src/app/chat/page.tsx'); checks=@('Test: flujo de cotización completo hasta envío por chat'); refs=@('ANALISIS-CRUZADO §9.5 A11','ROADMAP-IMPLEMENTACION §2.5'); kpi='Cotizaciones enviables sin salir del chat'; origen='Investigación A11 (P2)' }

Add-Issue @{ prefix='FEATURE'; id='A12'; title='Entrenamiento del agente con conversaciones exitosas'; priority='medium'; status='backlog'; type='feature'; area='agents'; milestone='Oleada 5 - Copiloto y asignación'; contexto='Usar conversaciones ganadas como ejemplos del prompt para mejorar la venta.'; alcance=@('Dataset de wins (conversaciones cerradas/comprador)','Inyección de ejemplos al prompt bajo consentimiento del tenant','Mecanismo de exclusión de PII'); deps=@('F1'); desbloquea=@(); archivos=@('helper-node/services/agentCore/llmClient.js','helper-node/services/agentConfig.js'); checks=@('Test: prompt incluye ejemplos anonimizados'); refs=@('ANALISIS-CRUZADO §9.5 A12'); kpi='Dataset de wins operativo'; origen='Investigación A12 (P2)' }

Add-Issue @{ prefix='FEATURE'; id='L3'; title='Routing automático por score y canal'; priority='critical'; status='backlog'; type='feature'; area='leads'; milestone='Oleada 5 - Copiloto y asignación'; contexto='Diseñado en CTX: hot -> asignación inmediata, warm -> cola, cold -> nurturing. Se construye sobre A6.'; alcance=@('Reglas de routing por score/etapa/canal','Colas: inmediata, estándar, nurturing','Alertas de asignación'); deps=@('A6','F1'); desbloquea=@('L10'); archivos=@('helper-node/index.js','docs/contextual/CTX-03-ABSTRACCION-CRM-TWENTY-FRAPPE-ERPNEXT.md'); checks=@('Test: lead hot se asigna inmediato; cold va a nurturing'); refs=@('ANALISIS-CRUZADO §9.3 L3','CTX-03 §3-4'); kpi='Hot atendidos <5 min'; origen='Investigación L3 (P0)' }

Add-Issue @{ prefix='VERIFICATION'; id='O5'; title='Cierre Oleada 5 - validación del copiloto y asignación'; priority='high'; status='backlog'; type='task'; area='consolidation'; milestone='Oleada 5 - Copiloto y asignación'; contexto='Gate: operador empoderado y reparto automático verificado.'; alcance=@('E2E chat con copiloto + handoff con contexto + asignación','Métricas de uso del copiloto','Actualizar docs'); deps=@('A1','A5','A6','A7','A9','A10','A11','A12','L3'); desbloquea=@('Oleada 6'); archivos=@('Avances/ESTADO-GENERAL.md'); checks=@('Todos los DoD de la oleada en verde'); refs=@('ROADMAP-IMPLEMENTACION §4 Oleada 5'); kpi='Oleada 5 100% verde'; origen='Gate de oleada' }

# ═══════════════════════ OLEADA 6 ═══════════════════════
Add-Issue @{ prefix='FEATURE'; id='F4'; title='Calendario de seguimientos y eventos (idea de usuario)'; priority='high'; status='backlog'; type='feature'; area='calendar'; milestone='Oleada 6 - Calendario y seguimiento (F4)'; roadmap=@('f4'); contexto='Vista por fecha con cards por grupo: cotizaciones, reuniones, compras y seguimientos; reactivo (el agente crea eventos) y pasivo (el operador agenda y recibe recordatorios).'; alcance=@('Entidad lead_events (tipo, fecha, estado, grupo/segmento, creado_por)','Hooks del grafo: cotización/reunión/cierre -> evento automático','Motor de programación de cadencias (A2) -> eventos','Página /calendar: vista mensual/semanal/día con cards por grupo y estado resumido','Recordatorios y feedback del agente por cliente vía /api/notifications'); deps=@('A2','F1','F2'); desbloquea=@('L10','Oleada 7'); archivos=@('helper-node/index.js','scripts/init-db.sql (lead_events)','frontend/src/app/calendar/page.tsx (nueva)','helper-node/services/agentCore/index.js (hooks)'); checks=@('E2E: conversación con cotización -> evento visible en calendario','Vista por día agrupa cards por grupo','Recordatorio llega al operador'); refs=@('ROADMAP-ITERATIVO-NUEVAS-FUNCIONALIDADES.md §3.4 F4','ANALISIS-CRUZADO gaps #3/#4'); kpi='>=90% de eventos generados automáticamente'; origen='Idea de usuario F4 + investigación A2/A3' }

Add-Issue @{ prefix='FEATURE'; id='A2'; title='Motor de cadencias de seguimiento ejecutable'; priority='critical'; status='backlog'; type='feature'; area='agents'; milestone='Oleada 6 - Calendario y seguimiento (F4)'; contexto='La secuencia followup existe en las plantillas y el nodo seguimiento la anuncia; falta un scheduler que la materialice en eventos programados.'; alcance=@('Job que materializa followup.sequence en lead_events con fechas','Pausas configurables (delay_days)','Escalación al agotarse (conecta R8)'); deps=@('F1'); desbloquea=@('F4'); archivos=@('helper-node/services/agentCore/nodes/followupNode.js','helper-node/templates/*.json (followup.sequence)','n8n/workflows/ o cron interno'); checks=@('Test: secuencia genera N eventos con fechas correctas','Eventos aparecen en /calendar'); refs=@('ANALISIS-CRUZADO §9.5 A2','CTX-04 §6'); kpi='100% de cadencias materializadas'; origen='Investigación A2 (P0)' }

Add-Issue @{ prefix='FEATURE'; id='A3'; title='Cola "qué hacer hoy" por operador'; priority='critical'; status='backlog'; type='feature'; area='agents'; milestone='Oleada 6 - Calendario y seguimiento (F4)'; contexto='Focus View (Pipedrive): el operador abre su lista de tareas/follow-ups con deadline para el día.'; alcance=@('Vista de tareas del día por operador (desde lead_events)','Filtros por grupo/etapa','Marcar hecho -> estado en el evento y en el lead'); deps=@('F4'); desbloquea=@('L10'); archivos=@('frontend/src/app/calendar/page.tsx','helper-node/index.js'); checks=@('E2E: operador ve su cola del día y marca eventos'); refs=@('ANALISIS-CRUZADO §9.5 A3','ROADMAP-IMPLEMENTACION §2.5'); kpi='>=90% de eventos del día completados'; origen='Investigación A3 (P0)' }

Add-Issue @{ prefix='FEATURE'; id='L9'; title='Alertas de lead caliente en tiempo real'; priority='medium'; status='backlog'; type='feature'; area='leads'; milestone='Oleada 6 - Calendario y seguimiento (F4)'; contexto='Avisar al operador en el momento en que un lead cruza el umbral hot.'; alcance=@('Detección al cruzar umbral (scoring/etapa)','Notificación en tiempo real (polling/socket) en el portal','Registro en audit_logs'); deps=@('F1'); desbloquea=@(); archivos=@('helper-node/index.js (scoring)','frontend/src/components/layout/StatusBar.tsx','helper-node/index.js (notifications :2992)'); checks=@('Test: cruce de umbral genera notificación'); refs=@('ANALISIS-CRUZADO §9.3 L9'); kpi='Alerta emitida <10s tras cruzar umbral'; origen='Investigación L9 (P2)' }

Add-Issue @{ prefix='FEATURE'; id='L10'; title='SLA de respuesta por categoría de lead'; priority='medium'; status='backlog'; type='feature'; area='leads'; milestone='Oleada 6 - Calendario y seguimiento (F4)'; contexto='Compromiso de tiempo: hot <5 min, warm <2h, con alerta por incumplimiento.'; alcance=@('Timer desde primer contacto hasta primera respuesta','SLA configurable por etapa/score','Alerta por incumplimiento + reporte semanal'); deps=@('F1','A6'); desbloquea=@(); archivos=@('helper-node/index.js','scripts/init-db.sql','frontend/src/app/reports/page.tsx'); checks=@('Test: hot sin respuesta a los 5 min dispara alerta'); refs=@('ANALISIS-CRUZADO §9.3 L10'); kpi='>=90% de SLAs cumplidos'; origen='Investigación L10 (P2)' }

Add-Issue @{ prefix='VERIFICATION'; id='O6'; title='Cierre Oleada 6 - validación del calendario'; priority='high'; status='backlog'; type='task'; area='consolidation'; milestone='Oleada 6 - Calendario y seguimiento (F4)'; contexto='Gate: seguimientos sin fugas y visibles por fecha/grupo.'; alcance=@('E2E: inbound -> cotización -> evento -> recordatorio -> cierre','Reporte de SLAs','Actualizar docs'); deps=@('F4','A2','A3','L9','L10'); desbloquea=@('Oleada 7'); archivos=@('Avances/ESTADO-GENERAL.md'); checks=@('Todos los DoD de la oleada en verde'); refs=@('ROADMAP-IMPLEMENTACION §4 Oleada 6'); kpi='Oleada 6 100% verde'; origen='Gate de oleada' }

# ═══════════════════════ OLEADA 7 ═══════════════════════
Add-Issue @{ prefix='FEATURE'; id='L7'; title='Reporte de fuentes con atribución'; priority='high'; status='backlog'; type='feature'; area='leads'; milestone='Oleada 7 - Cierre: auditoría y UX'; contexto='lead.source existe; falta el reporte de qué fuentes generan mejores resultados.'; alcance=@('Reporte: fuente -> leads -> respuestas -> etapas avanzadas','Vista en /reports','Consumo del atribución de campañas (C10)'); deps=@('F1','C10'); desbloquea=@(); archivos=@('frontend/src/app/reports/page.tsx','helper-node/index.js (trends :1336)'); checks=@('Test: reporte de fuentes correcto sobre dataset sintético'); refs=@('ANALISIS-CRUZADO §9.3 L7'); kpi='Atribución por fuente visible'; origen='Investigación L7 (P1)' }

Add-Issue @{ prefix='FEATURE'; id='L11'; title='A/B del modelo de scoring (reglas vs LLM)'; priority='medium'; status='backlog'; type='feature'; area='leads'; milestone='Oleada 7 - Cierre: auditoría y UX'; contexto='El compare por lead existe; falta comparación por cohortes para decidir el modelo por defecto.'; alcance=@('Cohortes A/B sobre leads nuevos','Métricas comparativas (acierto vs etapa alcanzada)','Selección de modelo por tenant'); deps=@('L6'); desbloquea=@(); archivos=@('helper-node/index.js (compare :1209, evaluate-llm :2325)'); checks=@('Test: cohortes producen métricas comparables'); refs=@('ANALISIS-CRUZADO §9.3 L11'); kpi='Modelo con mejor métrica activo'; origen='Investigación L11 (P2)' }

Add-Issue @{ prefix='FEATURE'; id='L14'; title='Feedback del operador sobre la calidad del score'; priority='low'; status='backlog'; type='feature'; area='leads'; milestone='Oleada 7 - Cierre: auditoría y UX'; contexto='Thumbs up/down en el detalle para retroalimentar el modelo.'; alcance=@('UI thumbs en el detalle del lead','Almacenamiento de feedback con lead/modelo/score','Consumo futuro en reentrenamiento'); deps=@('L8'); desbloquea=@(); archivos=@('frontend/src/app/leads/page.tsx','scripts/init-db.sql'); checks=@('E2E: registrar feedback y verlo persistido'); refs=@('ANALISIS-CRUZADO §9.3 L14'); kpi='Feedback registrado y auditable'; origen='Investigación L14 (P3)' }

Add-Issue @{ prefix='FEATURE'; id='L15'; title='Predicción de probabilidad de conversión'; priority='low'; status='backlog'; type='feature'; area='leads'; milestone='Oleada 7 - Cierre: auditoría y UX'; contexto='Probabilidad % simple basada en el histórico de etapas por segmento.'; alcance=@('Modelo simple: % de leads que llegaron a comprador por segmento/etapa','Mostrar % en el detalle y listado','Refinar cuando haya histórico maduro'); deps=@('F1','F3'); desbloquea=@(); archivos=@('helper-node/services/leadProfile.js','frontend/src/app/leads/page.tsx'); checks=@('Test: probabilidad coherente con dataset'); refs=@('ANALISIS-CRUZADO §9.3 L15'); kpi='Probabilidad visible en 100% de leads'; origen='Investigación L15 (P3)' }

Add-Issue @{ prefix='FEATURE'; id='C14'; title='Webhooks salientes de eventos de campaña'; priority='low'; status='backlog'; type='feature'; area='campaigns'; milestone='Oleada 7 - Cierre: auditoría y UX'; contexto='Notificar al sistema del cliente: estado, entrega, respuesta.'; alcance=@('Registro de endpoints de cliente (URL + secret)','Firma HMAC de eventos','Reintentos y log de entregas'); deps=@(); desbloquea=@(); archivos=@('helper-node/index.js (campañas)','helper-node/middleware/auth.js (HMAC)'); checks=@('Test: evento enviado y verificado por consumidor de prueba'); refs=@('ANALISIS-CRUZADO §9.1 C14'); kpi='Webhooks entregados con HMAC'; origen='Investigación C14 (P3)' }

Add-Issue @{ prefix='FEATURE'; id='C15'; title='Auditoría completa de campañas (actores y costos)'; priority='low'; status='backlog'; type='feature'; area='campaigns'; milestone='Oleada 7 - Cierre: auditoría y UX'; contexto='audit_logs cubre acciones; falta registrar costos por mensaje y traza completa por campaña.'; alcance=@('Costo por mensaje en deliveries','Vista de auditoría por campaña (quién creó/modificó/envió)','Exportación de la traza'); deps=@('C14'); desbloquea=@(); archivos=@('helper-node/index.js (campañas :244-378)','helper-node/services/auditLogger.js','scripts/init-db.sql'); checks=@('Test: traza completa incluye actores y costos'); refs=@('ANALISIS-CRUZADO §9.1 C15'); kpi='Traza 100% auditable'; origen='Investigación C15 (P3)' }

Add-Issue @{ prefix='FEATURE'; id='K15'; title='Borrado lógico con retención y GDPR'; priority='medium'; status='backlog'; type='feature'; area='contacts'; milestone='Oleada 7 - Cierre: auditoría y UX'; contexto='DELETE físico actual no cumple derecho al olvido; se requiere borrado lógico con retención.'; alcance=@('Campo deleted_at + exclusión de consultas','Retención configurable por plan','Flujo right-to-be-forgotten (anonimizar o borrar real tras retención)'); deps=@('D1'); desbloquea=@(); archivos=@('helper-node/index.js (DELETE lead :1474-1488)','scripts/init-db.sql','docs/contextual/CTX-06-LOGICA-NEGOCIO-INFORMACION.md'); checks=@('Test: borrado lógico oculta el lead de todas las vistas','Test: retención configura plazos'); refs=@('ANALISIS-CRUZADO §9.2 K15','CTX-06'); kpi='GDPR verificable'; origen='Investigación K15 (P3)' }

Add-Issue @{ prefix='VERIFICATION'; id='O7'; title='Cierre Oleada 7 - validación de auditoría y UX'; priority='high'; status='backlog'; type='task'; area='consolidation'; milestone='Oleada 7 - Cierre: auditoría y UX'; contexto='Gate: medir, mejorar y cumplir.'; alcance=@('Reportes de atribución y SLAs sobre datos reales','Prueba de webhook con consumidor','Auditoría GDPR','Actualizar docs'); deps=@('L7','L11','L14','L15','C14','C15','K15'); desbloquea=@('Oleada 8'); archivos=@('Avances/ESTADO-GENERAL.md'); checks=@('Todos los DoD de la oleada en verde'); refs=@('ROADMAP-IMPLEMENTACION §4 Oleada 7'); kpi='Oleada 7 100% verde'; origen='Gate de oleada' }

# ═══════════════════════ OLEADA 8 ═══════════════════════
Add-Issue @{ prefix='FEATURE'; id='F5'; title='Plantillas de campaña recomendadas por IA (idea de usuario)'; priority='high'; status='backlog'; type='feature'; area='templates'; milestone='Oleada 8 - Consolidación (F5)'; roadmap=@('f5'); contexto='Un agente plantillero analiza la lógica del negocio cargada y recomienda/genera plantillas por defecto para optimizar consumo y llamadas al agente.'; alcance=@('Endpoint POST /api/templates/generate (recomendación + generación)','Análisis cruzado: template de rubro + KB + históricos de campaña + brief del usuario','Selector de plantilla + botón "reescribir con IA" en el form de campaña','Detección de gaps de plantillas por canal/categoría','Generación 1 vez por segmento (integra F3) para ahorro de tokens'); deps=@('C12','C3'); desbloquea=@(); archivos=@('helper-node/index.js (templates :1898-1945)','helper-node/services/templateEngine.js','frontend/src/app/campaigns/page.tsx','frontend/src/app/templates/page.tsx','helper-node/services/agentCore/llmClient.js'); checks=@('Test templateGen.test.js: plantilla generada cumple max_length y variables válidas','E2E: generar plantilla y usarla en campaña','Preview OK antes de guardar'); refs=@('ROADMAP-ITERATIVO-NUEVAS-FUNCIONALIDADES.md §3.5 F5','ANALISIS-CRUZADO C7 + HubSpot AI writer'); kpi='>=50% de campañas nuevas con plantilla recomendada'; origen='Idea de usuario F5 + investigación C7' }

Add-Issue @{ prefix='DOC'; id='DOC-FINAL'; title='Actualización documental integral post-oleadas'; priority='medium'; status='backlog'; type='documentation'; area='consolidation'; milestone='Oleada 8 - Consolidación (F5)'; contexto='Reflejar el estado real post-implementación en toda la documentación viva.'; alcance=@('Actualizar TEC-02/TEC-06/MAESTRO-FUNCIONALIDADES-CORE','Actualizar Avances/ (ESTADO-GENERAL, LOGROS, OBJETIVOS-PENDIENTES)','Actualizar manuales de usuario','Verificar consistencia con el estándar TeVS'); deps=@(); desbloquea=@(); archivos=@('docs/tecnica/TEC-02-FUNCIONES-IMPLEMENTACION.md','docs/tecnica/TEC-06-FASES-IMPLEMENTACION.md','docs/maestro/MAESTRO-FUNCIONALIDADES-CORE.md','Avances/*.md'); checks=@('Cruce documental sin inconsistencias','CHANGELOG actualizado'); refs=@('TEC-04-SEGUIMIENTO-CAMBIOS-ITERACIONES.md'); kpi='Documentación 100% consistente con el código'; origen='Estándar del proyecto' }

Add-Issue @{ prefix='VERIFICATION'; id='O8'; title='Cierre Oleada 8 - consolidación integral'; priority='high'; status='backlog'; type='task'; area='consolidation'; milestone='Oleada 8 - Consolidación (F5)'; contexto='Gate final: suite e2e integral del anillo completo y regla de oro (todo activo y validado).'; alcance=@('Suite e2e: inbound -> etapa -> grupo/segmento -> campaña -> calendario -> reporte','Prueba de carga k6 (patrón existente)','TeVS + smoke + Jest completos','Registro de cierre en Avances/'); deps=@('F5','DOC-FINAL'); desbloquea=@(); archivos=@('e2e/specs/','scripts/tevs/','Avances/LOGROS.md'); checks=@('Suite integral verde','Todas las suites históricas en verde (176/22 + TeVS + e2e)'); refs=@('ROADMAP-IMPLEMENTACION §4 Oleada 8','FASE1-MVP-CRUZADO.md (regla de oro)'); kpi='Sistema completo validado end-to-end'; origen='Gate final' }

# ═══════════════════════ POSPUESTOS ═══════════════════════
Add-Issue @{ prefix='FEATURE'; id='C13'; title='Colas de campaña multi-tenant con prioridad por plan (POSPUESTO)'; priority='low'; status='blocked'; type='feature'; area='campaigns'; milestone='Pospuestos - Dependencias externas'; contexto='POSPUESTO: requiere SaaS multi-tenant real (OPS-MASTER). No bloquea ninguna oleada.'; alcance=@('Prioridad de envío por plan','Colas aisladas por tenant','Reactivar cuando el SaaS esté en marcha'); deps=@('SaaS multi-tenant (fuera de alcance actual)'); desbloquea=@(); archivos=@('OPS-MASTER.md'); checks=@('— (bloqueado)'); refs=@('ANALISIS-CRUZADO §9.1 C13','ROADMAP-IMPLEMENTACION §2.1'); kpi='—'; origen='Investigación C13 (P3) - pospuesto' }

Add-Issue @{ prefix='FEATURE'; id='K2'; title='Empresas de primer nivel (POSPUESTO)'; priority='medium'; status='blocked'; type='feature'; area='contacts'; milestone='Pospuestos - Dependencias externas'; contexto='POSPUESTO: requiere cerrar Twenty bidireccional (I1 no seleccionada). Twenty Companies ya existe como entidad externa.'; alcance=@('Entidad companies + relación lead->empresa','Sync con Twenty Companies','Reactivar con I1'); deps=@('I1 Twenty bidireccional (no seleccionada)'); desbloquea=@(); archivos=@('docs/context/TWENTY-CRM.md','DATA-MASTER.md'); checks=@('— (bloqueado)'); refs=@('ANALISIS-CRUZADO §9.2 K2','ROADMAP-IMPLEMENTACION §2.2'); kpi='—'; origen='Investigación K2 (P0) - pospuesto' }

Add-Issue @{ prefix='FEATURE'; id='K3'; title='Enriquecimiento de datos de contacto (POSPUESTO)'; priority='low'; status='blocked'; type='feature'; area='contacts'; milestone='Pospuestos - Dependencias externas'; contexto='POSPUESTO: requiere API externa con consentimiento del tenant. Opcional, no bloquea nada.'; alcance=@('Proveedor de enriquecimiento (industria, tamaño, redes)','Consentimiento por tenant','Reactivar cuando exista proveedor aprobado'); deps=@('Proveedor externo (sin definir)'); desbloquea=@(); archivos=@('—'); checks=@('— (bloqueado)'); refs=@('ANALISIS-CRUZADO §9.2 K3','ROADMAP-IMPLEMENTACION §2.2'); kpi='—'; origen='Investigación K3 (P1) - pospuesto' }

Write-Output '═════════ REPARACIÓN v3 COMPLETADA ═════════'
